---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
  - include_role:
      name: nginxinc.nginx_controller_generate_token
    vars:
        nginx_controller_user_email: azureuser@gmf.com
        nginx_controller_user_password: "{{ controller_pass }}"
        nginx_controller_fqdn: "{{ nginx_controller_fqdn }}"

  - name: Get controller api key for agent registration
    uri:
      url: "https://{{nginx_controller_fqdn}}/api/v1/platform/global"
      method: "GET"
      return_content: yes
      status_code: 200
      validate_certs: false
      headers:
        Cookie: "{{ nginx_controller_auth_token }}"
    register: nginx_controller_globals

  - name: Copy api_key to a variable
    set_fact:
      nginx_controller_api_key: "{{nginx_controller_globals.json.currentStatus.agentSettings.apiKey}}"

- hosts: localhost

  tasks:
  
  - name: install the agent
    include_role:
      name: nginxinc.nginx_controller_agent
    vars:
      nginx_controller_fqdn: "{{ nginx_controller_fqdn }}"
      nginx_controller_api_key: "{{ hostvars['localhost']['nginx_controller_api_key'] }}"
