- hosts: localhost
  gather_facts: no

  vars:
    vars:
    nginx_controller_user_email: azureuser@gmf.com
    nginx_controller_user_password: "{{ controller_pass}}"
    nginx_controller_fqdn: "{{ nginx_controller_fqdn }}"
    nginx_controller_auth_token:
    
    collections:
    - nginxinc.nginx_controller

  tasks:
    - name: Retrieve the NGINX Controller auth token
      include_role:
        name: nginxinc.nginx_controller_generate_token

    - name: Create a gateway
      include_role:
        name: nginxinc.nginx_controller_gateway
      vars:
        # controller.auth_token: output by previous role in example
        nginx_controller_environmentName: "dev"
        nginx_controller_gateway:
          metadata:
            name: lending
            displayName: "Shared Public Lending BU Gateway"
            description: "Routes all non special Lending applications"
          desiredState:
            ingress:
              uris:
                "http://mortgage.acmefinancial.net":
                  {}
                "https://mortgage.acmefinancial.net":
                  {}
                "http://ratecalculator.acmefinancial.net":
                  {}
                "https://ratecalculator.acmefinancial.net":
                  {}
              tls:
                certRef:
                  ref: "/services/environments/lending-prod/certs/star.acmefinancial.net"
                protocols:
                  - "TLSv1.3"
                  - "TLSv1.2"
              placement:
                instanceRefs:
                  - ref: "/infrastructure/locations/unspecified/instances/2"
                  - ref: "/infrastructure/locations/unspecified/instances/4"